version: '3'

services:
  web_app:
    image: web_store_app
    depends_on:
      rabbit_mq:
        condition: service_healthy
      pg:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/backend
    env_file:
      - .env
      - .flaskenv

  rabbit_mq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3

  pg:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=web_store
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 5s
      timeout: 10s
      retries: 5

  worker:
    image: web_store_app
    env_file:
      - .env
    entrypoint: ["/bin/bash","celery.sh"]


  nginx:
    image: nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_app

volumes:
  tmp: