from application_layer.user_auth import auth_blueprint
from application_layer.admin_resources import admin_blueprint
from application_layer.user_resource import user_blueprint
from application_layer.seller_resource import seller_blueprint
auth_blueprint = auth_blueprint
admin_blueprint = admin_blueprint
user_blueprint = user_blueprint
seller_blueprint = seller_blueprint
