"""Images

Revision ID: 6b8a50f8dcc4
Revises: fbb45d04129f
Create Date: 2023-12-05 16:34:16.347160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8a50f8dcc4'
down_revision = 'fbb45d04129f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
