"""Second migration

Revision ID: fbb45d04129f
Revises: 45d4ccba5c8a
Create Date: 2023-12-04 09:24:53.242479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb45d04129f'
down_revision = '45d4ccba5c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
